language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"

install:
  - pip install https://github.com/ros-infrastructure/rosdistro/archive/master.tar.gz
  - pip install argparse catkin-pkg rospkg PyYAML setuptools coverage

script:
  - nosetests --with-coverage

notifications:
  email: false
