language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"

install:
  - pip install argparse catkin-pkg rosdistro rospkg PyYAML setuptools coverage

script:
  - nosetests --with-coverage

notifications:
  email: false
